stages:          
  - test
  - build
  - release
  - deploy

# # TESTING STAGE
# e2e-test-job:
#   image: gradle:8-jdk21
#   stage: test    
#   script:
#     - echo "Running unit tests... This will take about 60 seconds."
#     - echo "Code coverage is 90%"

# integration-test-job:
#   image: gradle:8-jdk21
#   stage: test
#   script:
#     - echo "[*] Starting Integration Test...."
#     - echo "[*] Integration Test coverage is 100%"

# lint-test-job:   
#   image: gradle:8-jdk21
#   stage: test    
#   script:
#     - echo "Linting code... This will take about 10 seconds."
#     - echo "No lint issues found."

# # BUILD STAGE
# backend-build-job:      
#   image: gradle:8-jdk21
#   stage: build
#   environment: production
#   #rules:
#   # - if: $CI_COMMIT_REF_NAME == "main"
#   script:
#     - echo "Building the application..."
#     - ./gradlew bootJar
#     - echo "Building complete! :)"
#   artifacts:
#     paths:
#       - build/libs/*.jar 

# docker-deploy-job:
#   image: docker:20
#   stage: release
#   services:
#     - docker:dind
#   variables:
#     DOCKER_HOST: tcp://docker:2375/
#     DOCKER_DRIVER: overlay2
#     DOCKER_TLS_CERTDIR: ""
#   dependencies:
#     - backend-build-job
#   #rules:
#   # - if: $CI_COMMIT_REF_NAME == "main"
#   script:
#     - echo "Building & Deploying Docker Image..."
#     - docker logout
#     - echo -n "${CI_REGISTRY_PASSWORD}" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin    
#     - docker build --build-arg JAR_FILE=build/libs/*.jar -t gitlab.dit.htwk-leipzig.de:5050/projekt2024-s-audit-tool/backend .    
#     - docker push gitlab.dit.htwk-leipzig.de:5050/projekt2024-s-audit-tool/backend
#     - echo "[*] Image Build & Deployment was executed."

#DEPLOYMENT STAGE lolo
publish-job:      
  image: ubuntu:24.04
  stage: deploy  
  variables:
    DOCKER_IMAGE: gitlab.dit.htwk-leipzig.de:5050/projekt2024-s-audit-tool/backend:latest
    REMOTE_HOST: 141.57.8.208
    REMOTE_DOMAIN: https://sp08.imn.htwk-leipzig.de
    REMOTE_USERNAME: stud-fim
  environment: 
    name: production
  #rules:
  # - if: $CI_COMMIT_REF_NAME == "main"
  script:
    - apt update && apt upgrade -y
    - apt install ssh -y
    - mkdir -p ~/.ssh
    - echo "${PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
    - |
      CI_DEPLOY_PASSWORD=$CI_DEPLOY_PASSWORD CI_REGISTRY=$CI_REGISTRY CI_REGISTRY_USER=$CI_REGISTRY_USER ssh -t -i ~/.ssh/id_rsa $REMOTE_USERNAME@$REMOTE_HOST AAA=42 << 'EOF'
      env
      echo $CI_REGISTRY
      echo $AAA
      EOF
